### PR TITLE
added requirements.txt for python dependencies, update .travis.yml

### PR DESCRIPTION
**Pull request by evanbiederstedt**
This is a somewhat aesthetic PR:

* Added a requirements.txt for python dependencies, using the most current versions. This is useful I find if one is working with a virtualenv. 

* Modified the .travis.yml to install these dependencies with several versions of python3.x (the most recent releases). It appears scipy has issues compiling with python3.8, so I skipped this. I saw no reason not to compile nanopolish afterwards. Given Travis-CI tests run in parallel, I don't see a big problem adding these (though sometimes the build stalls due to internet connection issues, etc.)

* Updated `libhdf5-serial-dev` to `libhdf5-dev`. I don't see the reason for using the transitional package, but I could be missing something: https://packages.debian.org/stretch/libhdf5-serial-dev

* Regarding python library versions, the scripts often recommend older libraries---perhaps these should be changed? I didn't feel comfortable changing these comments without more tests. 

* Also added "names" to the build matrix, as I find this useful---the user immediately understands the motivation behind why those Travis-CI tests are used. Perhaps these should be modified, as I'm just guessing why they're there. 

Tests appear to pass here: 
https://travis-ci.org/evanbiederstedt/nanopolish/builds/629557653

Feel free to change whatever of course---I'm not sure if you prefer merge to master, or elsewhere.

### CODE REVIEW

**Comment by jts** [comment]
Hi @evanbiederstedt,

Thanks for the PR! Can you remove the .DS_Store file?

Jared

**Comment by evanbiederstedt** [comment]
Hi @jts 

> Can you remove the .DS_Store file?

Somehow missed that file, sorry about that! Now removed. 

Thanks, Evan

**Comment by jts** [comment]
thanks, merged!

**Comment by evanbiederstedt** [comment]
@jts 

Thanks! I'll go ahead and delete the branch

**Pull request merged**
